name = "JHistint"
uuid = "f9cb9bd9-7498-4774-9389-dea22f18ae4d"
authors = ["niccolò_mandelli <n.mandelli2@campus.unimib.it>"]
version = "0.1.1"

[compat]
julia = "1.8.5"
HTTP = "1.7.4"
JSON = "0.21.3"
ZipFile = "0.10.1"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

